# Generated by Django 3.2.8 on 2021-10-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_letter', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['rating_letter', 'details'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Select a genre for this book')),
                ('rating', models.ForeignKey(help_text='Enter a movie rating category (e.g. PG-13)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviesdb.grade')),
            ],
        ),
    ]
